[alias]
ck = "check --workspace --all-features --all-targets --exclude kaiki_napi"
lint = "clippy --workspace --all-targets --all-features --exclude kaiki_napi -- --deny warnings"

[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"
