name: Check Version
description: Detect version changes in a package.json file

inputs:
  package-json-path:
    description: Path to the package.json file to check
    required: true

outputs:
  version:
    description: The current version
    value: ${{ steps.version.outputs.version }}
  changed:
    description: Whether the version has changed
    value: ${{ steps.version.outputs.changed }}

runs:
  using: composite
  steps:
    - uses: EndBug/version-check@095362f3cd50f690c8fa0e6afeea81834bd8d320 # v3.0.0
      id: version
      with:
        file-name: ${{ inputs.package-json-path }}
        diff-search: true
