name: autofix.ci # For security reasons, the workflow in which the autofix.ci action is used must be named "autofix.ci".

permissions: {}

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-node
      - run: pnpm install --frozen-lockfile
      - uses: ./.github/actions/setup-rust
        with:
          restore-cache: true
          cache-key: warm
          tools: just,cargo-shear@1.11.2,dprint
          components: rustfmt
      - name: cargo-shear
        id: shear
        shell: bash
        run: |
          if ! cargo shear --fix; then
            echo "shear=true" >> $GITHUB_OUTPUT
          fi
      - name: Update lock file # `cargo metadata` re-resolves and rewrites Cargo.lock without compiling
        run: cargo metadata --format-version=1 > /dev/null
        if: ${{ steps.shear.outputs.shear == 'true' }}
      - run: just fmt
      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8 # v1.3.3
        with:
          fail-fast: false
