name: CI Security

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
  pull_request:
    paths:
      - ".github/**"

permissions: {}

jobs:
  zizmor:
    name: Workflow Security
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
      - uses: github/codeql-action/upload-sarif@820e3160e279568db735cee8ed8f8e77a6da7818 # v3
        with:
          sarif_file: results.sarif
          category: zizmor
