# Run `cargo-llvm-lines` for finding out bloat generic functions

name: Cargo LLVM Lines

permissions: {}

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  bloat:
    name: Cargo LLVM Lines
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-rust
        with:
          cache-key: warm
          tools: cargo-llvm-lines
      - name: Run
        run: cargo llvm-lines -p kaiki_diff | head -20 > $GITHUB_STEP_SUMMARY
